//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities.Projects
{
    using System;
    using System.Collections.Generic;
    
    public partial class PepoleTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PepoleTBL()
        {
            this.OrganizationsProjects = new HashSet<OrganizationsProject>();
        }
    
        public int PeopleID { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public string MobilePhone { get; set; }
        public string LandLineExt { get; set; }
        public string EmailAdress { get; set; }
        public int OrgID { get; set; }
    
        public virtual OrganizationBasic OrganizationBasic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationsProject> OrganizationsProjects { get; set; }
    }
}
