//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities.Archive
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUpDocumentsCircle
    {
        public int ArchiveID { get; set; }
        public System.DateTime EventDatetime { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> EventType { get; set; }
    
        public virtual ArchiveTBL ArchiveTBL { get; set; }
        public virtual EventType EventType1 { get; set; }
    }
}
