//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities.ToDoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionTBL
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeActionID { get; set; }
        public Nullable<int> ActionTaken { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Notes { get; set; }
        public string Attachments { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual EmployeeTask EmployeeTask { get; set; }
    }
}
