//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities.ToDoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActionType()
        {
            this.ActionTBLs = new HashSet<ActionTBL>();
        }
    
        public int ID { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public Nullable<decimal> PercentageAdd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionTBL> ActionTBLs { get; set; }
    }
}
