//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities.ToDoList
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskOperation()
        {
            this.EmployeeTasks = new HashSet<EmployeeTask>();
            this.TaskOperations1 = new HashSet<TaskOperation>();
        }
    
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> CreatorEmp { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> DeliverableID { get; set; }
        public Nullable<bool> TaskStatus { get; set; }
        public Nullable<int> TaskType { get; set; }
        public Nullable<int> TaskProierty { get; set; }
        public string Attachments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTask> EmployeeTasks { get; set; }
        public virtual ProiertyType ProiertyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskOperation> TaskOperations1 { get; set; }
        public virtual TaskOperation TaskOperation1 { get; set; }
        public virtual TaskType TaskType1 { get; set; }
    }
}
